[
  {
    "title": "Mayotte — géographie et histoire",
    "category": "caribou",
    "summary": "Archipel volcanique, climat, étapes vers la départementalisation (2011).",
    "content": "GÉOGRAPHIE\nSituée dans l'hémisphère sud, à l'entrée du Canal du Mozambique, à mi-chemin entre Madagascar et l'Afrique, Mayotte (\"l'île hippocampe\") est un archipel volcanique de 374 km². Elle comprend deux îles principales et une trentaine de petits îlots, dans un lagon de plus de 1 500 km².\nL'îlot de Pamandzi et le rocher de Dzaoudzi, reliés par le \"Boulevard des Crabes\", forment Petite-Terre. Le chef-lieu administratif est à Dzaoudzi, mais l'activité économique se concentre autour de Mamoudzou, en Grande-Terre.\nMayotte est la plus ancienne île de l'archipel des Comores (environ 8 millions d'années), avec un relief moins accentué du fait de l'érosion. Elle possède l'un des plus grands lagons du monde, délimité par une barrière de corail de plus de 160 km.\n\nCLIMAT\nTropical humide (moyenne annuelle 25,6°C), deux saisons :\n- Saison des pluies (octobre-mars) : mousson du nord, fortes températures et humidité, 80% des précipitations annuelles. Saison des cyclones, mais Mayotte est protégée à l'est par Madagascar et peu exposée au risque cyclonique.\n- Saison sèche (avril-septembre) : alizés du sud-est, climat plus frais et moins humide.\n\nHISTOIRE — DES ORIGINES À LA FRANCE\nPeuplement originel d'origine bantoue (Vème-VIIIème siècle). Influences arabes (culture swahilie, religion musulmane), sultanats rivaux dans l'archipel. Premiers Européens (Portugais, Français) vers le XVème siècle.\nFin XVIIIème-début XIXème : troubles violents (razzias d'esclaves malgaches), population réduite à 3 000 personnes.\n\n25 avril 1841 : le sultan Andriantsouli cède Mayotte à la France — début du protectorat français. Esclavage aboli en 1846.\n1886-1892 : protectorat français étendu aux autres îles des Comores.\n1946 : statut de Territoire d'Outre-mer pour l'archipel des Comores.\n\nVERS LA DÉPARTEMENTALISATION\nDécembre 1974 : référendum sur l'indépendance — Mayotte vote à 63,8% pour rester française.\nFévrier 1976 : nouvelle consultation, 99,4% pour le maintien dans l'ensemble français.\n1976 : statut provisoire de Collectivité Territoriale de la République.\n29 mars 2009 : 95,2% des Mahorais votent pour la départementalisation.\n31 mars 2011 : Mayotte devient le 101e département français.\n1er janvier 2014 : Mayotte accède au statut de région ultrapériphérique (RUP) de l'Union Européenne, ouvrant l'accès aux fonds structurels européens."
  },
  {
    "title": "Mayotte — démographie et conditions de vie",
    "category": "caribou",
    "summary": "Forte natalité, pauvreté, conditions de logement précaires — contexte essentiel pour la pratique médicale.",
    "content": "DÉMOGRAPHIE\nRecensement 2022 : environ 300 000 habitants (805 hab/km²), contre 25 000 dans les années 1970.\nForte natalité + flux migratoire (majoritairement comorien, de plus en plus est-africain) : excédent migratoire de 32 500 personnes entre 2012 et 2017 (surtout femmes 15-34 ans avec enfants).\nMayotte est aussi une terre d'émigration méconnue : 25 900 natifs ont quitté le territoire entre 2012 et 2017.\nPlus de la moitié des adultes de l'île n'y sont pas nés (>40% originaires des Comores). Près de la moitié de la population n'a pas la nationalité française, mais un tiers des étrangers de l'île y sont nés.\n\nFÉCONDITÉ ET NATALITÉ\n5,0 enfants par femme à Mayotte (vs 1,9 en métropole). 10 795 naissances en 2022 (3/4 de mères étrangères, 1/2 de pères étrangers, un peu plus de la moitié avec au moins un parent français).\n\nCONDITIONS DE VIE\nEn 2011 : 84% de la population sous le seuil de pauvreté (959€/mois/ménage) contre 16% en métropole.\nEn 2018 : seulement 1/3 des 15-64 ans a un emploi ; taux de chômage 35%. 6 jeunes sur 10 (20-29 ans) sans emploi ni formation. Les cultures vivrières privées (bananes, manioc) restent essentielles à l'alimentation de nombreux foyers.\n\nLOGEMENT\n1/10 sans électricité, 1/3 sans eau courante, 6/10 sans confort sanitaire de base (eau intérieure + toilettes + douche/baignoire). Près de 4 logements sur 10 en matériaux fragiles (tôle, bois, végétal, terre) — 65% chez les étrangers contre 25% chez les Français natifs de l'île.\n\nDÉMOGRAPHIE SANITAIRE\nPopulation jeune : la moitié a moins de 18 ans. Taux de décès par habitant le plus faible de France (2,9/1000 en 2018), MAIS les taux de décès par tranche d'âge sont plus élevés qu'en métropole. Mortalité infantile élevée (9,8/1000) ainsi que celle des seniors.\n\nPROTECTION SOCIALE\nPas de CMU-C, ni d'AME, ni d'ACS à Mayotte. Accès aux soins gratuit pour les résidents réguliers au CHM. Les non-affiliés doivent acquitter un forfait, sauf en cas de risque vital, épidémique, ou pour la maternité et la pédiatrie.\n\nÉDUCATION\nScolarisation de masse récente (1973) — faible niveau d'éducation chez les plus de 40 ans. En 2002, 44% de la population n'avait jamais été scolarisée (mais 60% savaient lire/écrire l'arabe via l'école coranique). En 2015, plus de 5 jeunes sur 10 en situation d'illettrisme, 75% des 17-24 ans en grave difficulté de lecture."
  },
  {
    "title": "Mayotte — système de santé et CHM",
    "category": "caribou",
    "summary": "Densité de soignants, organisation du CHM en dispensaires, spécialités absentes nécessitant une EVASAN.",
    "content": "DENSITÉ DES PROFESSIONNELS DE SANTÉ\nNettement inférieure à la métropole, à l'exception des sages-femmes (densité double).\n244 médecins en activité (01/01/2019), 89 masseurs-kinésithérapeutes (01/01/2018), 720 infirmiers (01/01/2018).\n\nORGANISATION DU CHM\nL'offre de soins est majoritairement publique. Le Centre Hospitalier de Mayotte (CHM) gère l'offre de médecine générale via des dispensaires : 4 centres de référence et 13 centres de consultations, répartis en 5 secteurs (Nord, Centre, Sud, Grand Mamoudzou, Petite-Terre).\n\nLe CHM de Mamoudzou regroupe le plateau technique complet : urgences, laboratoire, radiologie, hospitalisation médecine/chirurgie, pédiatrie, réanimation, maternité.\n\nAVIS SPÉCIALISÉS\nC'est au CHM que se font la majorité des avis spécialisés : cardiologie, endocrinologie, pneumologie, rhumatologie, médecine interne, gastro (FOGD, coloscopie, suivi VHB), rééducation, néphrologie (RDV à prendre en médecine externe), dermatologie (RDV à Action Santé ou lors des missions), ORL, ophtalmologie, oncologie (médecine ambulatoire).\n\nMISSIONS PONCTUELLES\nDes spécialistes viennent fréquemment de La Réunion pour des missions temporaires (chirurgie infantile, neurologie, rhumatologie, dermato...). Le planning est communiqué par le secrétariat des services concernés (à consulter sur la messagerie interne).\n\nSPÉCIALITÉS ABSENTES (recours à l'EVASAN)\nNeurochirurgie, chirurgie cardiaque, cardiologie interventionnelle ne sont pas représentées sur le territoire. En cas d'urgence relevant de ces spécialités, les patients sont évacués vers La Réunion ou la métropole (évacuation sanitaire = EVASAN)."
  },
  {
    "title": "Arrivée à Mayotte — candidature et contrat",
    "category": "caribou",
    "summary": "Process de candidature, types de contrats, avantages du PH contractuel.",
    "content": "CANDIDATURE\nPour candidater, il suffit de passer par le chef de service qui valide la candidature auprès des affaires médicales du CHM.\n\nTYPES DE CONTRATS\n- Contrats de FFI pour les licences de remplacement\n- Contrats de PH contractuels ou PH titulaires pour les médecins thésés\nDurée minimum : 1 mois.\n\nRECOMMANDATION\nUne expérience de 3 mois est conseillée — elle permet à la fois de découvrir la médecine mahoraise et d'avoir le temps de découvrir l'île.\n\nAVANTAGES DU CONTRAT PH CONTRACTUEL\n- Billets aller-retour pris en charge\n- Voiture de location prise en charge 3 mois\n- Logement CHM pris en charge 6 mois\n- Rémunération selon la loi RIST II"
  },
  {
    "title": "Arrivée à Mayotte — logistique pratique (avion, logement, badge)",
    "category": "caribou",
    "summary": "Du débarquement à l'aéroport jusqu'à l'installation : voiture, badge, accès informatique.",
    "content": "ARRIVÉE PAR AVION\nL'avion atterrit à Dzaoudzi (Petite-Terre), où se situe l'aéroport. Un agent du CHM (service logement) attend pour remettre la voiture et les clés du logement.\nContact service logement : 06 39 68 79 45\n\nSI LA BARGE EST NÉCESSAIRE (pour rejoindre Mamoudzou)\nPrendre un taxi (environ 2€, facilement trouvable devant l'aéroport) jusqu'au port, puis rejoindre le point de ralliement au bar \"camion rouge\" (en sortant à gauche de la barge en arrivant à Mamoudzou).\nUn agent CHM y remet ensuite le véhicule.\n\nFIN DE CONTRAT\nLa restitution se fait à l'agence de location pour la voiture, et au PC sécurité de Mamoudzou (entrée du CHM) pour les clés du logement.\n\nBADGE\nÀ récupérer au service badge du CHM, dans l'un des bâtiments administratifs en face de l'entrée du CHM — c'est aussi là que se trouvent les affaires médicales si la signature du contrat est nécessaire sur place.\n\nACCÈS INFORMATIQUE — À FAIRE AVANT L'ARRIVÉE\nAppeler le standard (0269618000) puis :\n- Service DxCare (poste 3750) pour les identifiants de connexion\n- Service Informatique (poste 3700) pour les identifiants de session DxCare"
  },
  {
    "title": "Culture mahoraise — religion, rapport à la maladie et à la mort",
    "category": "caribou",
    "summary": "95% musulmane, fatalisme face à la maladie chronique, notion de djinn — clés de compréhension essentielles.",
    "content": "CONTEXTE RELIGIEUX\n95% de la population est musulmane, pratiquant pieusement mais de manière modérée. L'Islam occupe une place importante dans la société mahoraise, associé à une spiritualité d'origine africaine (notion de djinn/esprit).\n\nRAPPORT À LA MALADIE CHRONIQUE\nLa notion de pathologie chronique est souvent difficile à appréhender. Annoncer un diagnostic grave ou une complication sévère (ex: liée au diabète) peut amener le patient à répondre que seul Allah décide du droit de vie ou de mort. Cette résilience face à la maladie et à la mort entraîne de fréquentes ruptures de traitement.\n\n\"CRISES DE DJINN\" (possession par esprit)\nPeuvent évoquer des somatisations de traumatisme personnel, des spasmophilies ou crises d'angoisse réactionnelles, surtout chez les jeunes filles. Devant ces tableaux (parfois de type pseudo-épileptique), rechercher à l'anamnèse un passé traumatisant ou des épreuves psychologiques. Rassurer la personne et s'appuyer sur les membres mahorais de l'équipe soignante, qui savent trouver les mots pour apaiser le patient.\n\nMÉDECINE TRADITIONNELLE\nLes patients associent fréquemment la médecine traditionnelle (tisanes, décoctions) à la médecine occidentale, utilisant les deux en alternance. À garder en tête lors des anamnèses : par exemple, certaines plantes diurétiques/hypotensives utilisées en automédication peuvent être hypokaliémiantes ; l'ingestion d'argile blanche peut être en lien avec une anémie."
  },
  {
    "title": "Culture mahoraise — communication, Ramadan, et le Mcarara/MSada",
    "category": "caribou",
    "summary": "Tutoiement, pudeur, jeûne du Ramadan, et la pratique d'entraide entre soignants.",
    "content": "COMMUNICATION AVEC LE PATIENT\n- Le tutoiement est souvent la règle.\n- Certains patients peuvent paraître peu communicants, évitants — traduisant plutôt un comportement pudique que de l'hostilité.\n- La douleur peut être sous-évaluée ou sur-évaluée selon les profils — à intégrer dans l'évaluation clinique.\n\nRAMADAN\nLe jeûne se pratique 1 mois par an selon un calendrier lunaire défini par le Cadi. Durant cette période, les musulmans ne boivent ni ne mangent du lever au coucher du soleil. Les ruptures de traitement sont nombreuses. Solutions possibles à proposer médicalement : prières allégées, ou adaptation des prises médicamenteuses pour raison de santé.\n\nLE MCARARA / MSADA — PRATIQUE D'ENTRAIDE ENTRE SOIGNANTS\nEn raison du manque d'accès aux soins, les soignants mahorais ont fréquemment besoin d'avis médicaux pour eux-mêmes ou leurs familles, souvent intercalés entre les consultations aiguës.\nCette pratique est appelée localement \"Mcarara\" ou \"Business\" — le terme préféré est \"MSada\" (entraide), plus juste sur le fond.\nConseil : ne pas se braquer, temporiser si une urgence est en cours, mais consulter ces demandes dès que possible. C'est une pratique très répandue à Mayotte qui favorise une bonne entente avec les équipes soignantes, qui comptent beaucoup sur cette aide au vu de la difficulté d'accès aux soins."
  },
  {
    "title": "Dispensaire Kahani — horaires et organisation des consultations",
    "category": "caribou",
    "summary": "Horaires d'ouverture, capacité de consultation, fonctionnement matin/après-midi.",
    "content": "HORAIRES\nKahani : 7h-17h. Sada : 7h-13h. La permanence de soins (PDS), pour les soins urgents, est ouverte 24h/24.\n\nLE MATIN\nDès 6h30, l'agent de sécurité et l'infirmier d'orientation à l'accueil (IAO) trient les patients vers les différents soignants (urgences, consultations aiguës/chroniques, injection d'insuline, pansements, RDV bilans...).\nCapacité théorique : 25 consultations par médecin, soit environ 75 patients le matin.\nLes patients sont enregistrés au bureau des entrées, reçoivent un bon de circulation (retrait des traitements à la pharmacie du dispensaire, ouverte 8h-15h en semaine, fermée le week-end), puis sont reçus au BOX ACCUEIL ET ORIENTATION où un AS prend les paramètres et les inscrit sur DxCare. Les patients francophones reçoivent la mention \"F\" sur leur bon.\n\nL'APRÈS-MIDI\nRéservé aux 15 consultations sur rendez-vous, plus 20 tickets de consultations non programmées. À partir de 17h, les médecins basculent sur la permanence de soins.\n\nPRISE DE RDV SPÉCIALISTES\nLors des consultations, les patients sont dirigés vers le secrétariat pour la prise de RDV avec les spécialistes, notamment au CHM.\n\nACCÈS HORS HORAIRES\nL'accès à la PDS en dehors des horaires du bureau des entrées (7h-17h) nécessite un enregistrement par un référent de la régie (AS) directement dans la PDS. Après 17h, tous les patients sont paramétrés à la PDS."
  },
  {
    "title": "Permanence de soins (PDS) — fonctionnement et transferts",
    "category": "caribou",
    "summary": "Locaux, déclenchement de transfert (14 vs 15), gestion des consultations semi-urgentes en garde.",
    "content": "PRÉSENTATION\nLa PDS prend en charge les patients nécessitant des soins non différables (plaies, urgences, accueil des patients en ambulance). Pas d'hospitalisation possible : la durée de séjour maximale est de 6h.\n\nLOCAUX\n- Salle de déchoquage : 2 brancards avec scopes (prises en charge urgentes, plaies)\n- Salle d'observation de courte durée : 2 brancards (lit 1, lit 2) + 2 fauteuils (attentes de transfert, asthme...)\n- Seconde salle d'observation : 1 lit adulte + 1 lit pédiatrique + 2 fauteuils (surveillance SRO)\n\nLes patients vus en consultation peuvent être envoyés aux urgences pour ECG, injections, aérosols, ou prise en charge d'urgence.\n\nTRANSFERTS\n- Transfert vers les urgences de Mamoudzou : nécessite l'accord du médecin régulateur du SAMU (poste 14), qui déclenche le transport.\n- Le 15 reste le numéro pour les urgences vitales, avec déclenchement SMUR (4x4 ou hélicoptère).\n- Des ambulances libérales peuvent être appelées pour les patients affiliés à la CSSM.\n\nORGANISATION PENDANT LES GARDES\nÀ l'accueil PDS, les patients sont enregistrés par les aides-soignants, puis pris en charge par le médecin et l'IDE.\nLe médecin peut réadresser aux consultations du lendemain les patients ne nécessitant pas de prise en charge urgente, après s'être assuré de l'absence de gravité. Entre 17h et 19h généralement, la PDS renvoie les consultations semi-urgentes vers les bureaux de consultation.\n\nCONSEIL DE COMMUNICATION\nÉviter \"vous n'êtes pas une urgence\" (rarement efficace). Préférer : \"je vous dépanne de votre motif et vous pourrez revenir demain matin en consultation\"."
  },
  {
    "title": "Effectifs et planning médical — Kahani",
    "category": "caribou",
    "summary": "Répartition K1/K3, gardes, jours fériés musulmans, référents locaux.",
    "content": "EFFECTIFS THÉORIQUES\n\nK1 (7h-13h) — 5 médecins :\n- 3 en consultations aiguës (dont 1 se détache au tri)\n- 1 à la permanence de soins (urgences)\n- 1 sur les consultations chroniques (KRO)\nD'autres bureaux s'ouvrent selon l'effectif disponible, pour accueillir des intervenants extérieurs (psychiatrie adulte, pédiatrie, assistant social, psychologue, téléconsultation...).\n\nK3 (13h-19h) — 3 médecins :\n- 2 en consultation (RDV + consultations aiguës semi-urgentes)\n- 1 en PDS\n\nUn médecin sans patient peut aider ses collègues.\n\nCCP DE SADA\nUn médecin consulte le matin en semaine (7h-13h, code \"S\" sur le planning).\n\nSAMEDI MATIN\n3 médecins en K1.\n\nGARDES\n- Samedi après-midi : 13h-19h\n- Dimanche et jours fériés : 7h-19h (parfois partagé en deux)\n- Nuits : 19h-7h\nLes jours fériés musulmans ne sont pas toujours connus à l'avance — date précise parfois communiquée seulement la veille.\n\nRÉFÉRENTS LOCAUX (au moment de la rédaction du document, à actualiser)\nSerge Garnier : référent des consultations chroniques, tient les statistiques patients\nIssoufa Maoulida : médecin mahorais de l'équipe, ressource précieuse pour les particularités locales\nAdrien Cussac : chef de service"
  },
  {
    "title": "Organisation du tri — méthode et objectifs",
    "category": "caribou",
    "summary": "Rôle de l'IAO et du Médecin d'Accueil et Orientation (MAO), tickets rouge/blanc, limite de 75 patients.",
    "content": "CONTEXTE\nLe parcours de soin est souvent chamboulé par une pression trop forte au portail par rapport à la capacité de consultation (25 consultations théoriques par médecin de K1).\n\nORGANISATION DU TRI À KAHANI\nUn médecin de consultation devient Médecin d'Accueil et Orientation (MAO), avec un AS, à l'ALGECO face à l'entrée du dispensaire.\nObjectifs : trier les problématiques simples/rapides vs complexes, désengorger le dispensaire et le BOX AO, réaliser un double regard (IAO puis MAO) pour ne pas manquer une urgence, bien orienter le patient et prescrire ce qui accélère sa prise en charge.\n\nL'ALGECO est équipé : DYNAMAP, glycémie capillaire, balance adulte et pédiatrique. Consultation possible sur chaise ou brancard.\n\nDÈS 6H30 — RÔLE DE L'IAO\nDescend au portail, récupère la liste des patients établie par la sécurité. Dépiste en priorité :\n- Fièvre mal tolérée, notamment chez l'enfant\n- Signes de gravité (détresse respiratoire, trouble de la vigilance, déshydratation sévère)\n- Patients venant pour des résultats de bilan\nNote la date et la température de chaque patient examiné.\n\nORIENTATION DÉCIDÉE PAR L'IAO\n- Ticket rouge : urgence\n- Consultation semi-urgente \"complexe\" : paramétrage au local IAO puis bureau de consultation (mention \"F\" si patient francophone)\n- Ticket blanc \"tri\" : motif simple et non différable, attente sous la varangue de la maternité ou face au rond-point, envoyé au MAO (limite 25-30 tickets selon afflux)\n\nDÈS 7H — RÔLE DU MAO\nDescend avec l'AS AO à la tente : consultation rapide (viroses, parasitoses, problématiques non complexes) et réorientation si besoin des cas complexes. Peut prescrire directement les examens réalisables au box IAO (BU, bHCG, palu, dengue, hémocue, cétonémie...).\n\nEXEMPLES DE CONSULTATIONS SIMPLES (MAO)\nVirose bénigne sans gravité (rhinopharyngite, varicelle, OMA, angine), parasitose (gale, parasitoses digestives), mycose bénigne (teignes, dermatophytie des plis), mise à jour vaccinale.\n\nRÈGLE ABSOLUE\nAucun patient ne doit sonner à la PDS sans être passé par l'IAO — le réorienter avec patience vers l'IAO si besoin.\n\nL'APRÈS-MIDI\nL'IAO (assisté d'un médecin si besoin) redistribue jusqu'à 20 tickets de consultation. Si effectif suffisant, les secrétaires peuvent inscrire 15 consultations programmées en plus. Au-delà des 20 tickets, chaque demande est examinée au cas par cas. À partir de 17h, le bureau des entrées ferme — passage obligatoire par la PDS.\nLe bureau de consultation 1 peut être dédié à l'aigu, le bureau 2 aux RDV si nécessaire."
  },
  {
    "title": "DxCare — informatique et logiciel dossier patient",
    "category": "caribou",
    "summary": "Logiciel utilisé pour dossiers, résultats, comptes-rendus. Contacts en cas de problème.",
    "content": "Le logiciel utilisé au CHM est DxCare — pour les dossiers patients, l'accès aux résultats biologiques et d'imagerie, et les comptes-rendus de consultation ou d'hospitalisation. La prise en main est généralement aisée, un collègue peut accompagner la découverte à l'arrivée.\n\nEN CAS DE PROBLÈME\nProblème de session : poste 3700 (informatique)\nProblème DxCare : poste 3750\n\nRéclamation possible via ticket GLPI, accessible dans INTRANET sur le bureau, onglet INTRANET → \"Demande intervention informatique\"."
  },
  {
    "title": "Carnet de santé du patient — usage et importance",
    "category": "caribou",
    "summary": "Carnet bleu (général) ou rouge (drépanocytaire) — antécédents, vaccins, preuve de résidence.",
    "content": "Les patients présentent leur carnet de santé (généralement petit carnet bleu ; rouge pour les patients drépanocytaires) à leur arrivée en consultation.\n\nCONTENU\nVaccins, antécédents, rendez-vous, comptes-rendus — le patient ne connaît souvent ni sa pathologie ni son traitement précis. Il est fortement recommandé de le feuilleter systématiquement pour ne pas méconnaître une allergie, un antécédent notable, ou pour vérifier le statut vaccinal.\n\nAUTRE FONCTION\nCe carnet constitue aussi la preuve de résidence sur le territoire mahorais, nécessaire pour l'obtention d'un titre de séjour.\n\nPRATIQUE\nLe compte-rendu de consultation et la prescription sont rédigés sur DxCare, imprimés puis collés dans le carnet. L'écriture manuscrite directe dans le carnet reste également possible."
  },
  {
    "title": "Déclenchement MCS (Médecin Correspondant SMUR)",
    "category": "caribou",
    "summary": "Sortie en urgence vitale sur demande de la régulation, matériel à emporter, certificats de décès à domicile.",
    "content": "PRINCIPE\nSur demande de la régulation, le médecin peut être amené à sortir dans le cadre d'une urgence vitale en tant que MCS (Médecin Correspondant SMUR) — le SMUR est alors systématiquement déclenché. Pas de visite médicale classique en dehors de ce cadre.\n\nACCOMPAGNEMENT\nLe jour : ambulancier + IDE (celui de pansement). La nuit : ambulancier seul.\n\nMATÉRIEL\nSac d'urgence + défibrillateur (localisés en UHCD) + scope. Aspiration et oxygène sont sur le chariot d'urgence, en salle brancard ou dans l'ambulance.\n\nCERTIFICATS DE DÉCÈS À DOMICILE\nLa régulation peut demander une sortie pour signer un certificat de décès à domicile — toujours accompagné d'un ambulancier. Il convient de refuser cette sortie si elle laisserait le dispensaire sans médecin.\n\nAPRÈS L'INTERVENTION\nChaque médecin ayant utilisé le sac est responsable de sa réfection à son retour, avec l'aide de l'IDE et des ambulanciers. Astuce pratique : mettre tout le matériel utilisé dans un sac poubelle pendant l'intervention pour faciliter la réfection ensuite."
  },
  {
    "title": "Équipe paramédicale du dispensaire — rôles et répartition",
    "category": "caribou",
    "summary": "Traducteurs, bureau des entrées, IDE, AS, secrétaires, sécurité — qui fait quoi.",
    "content": "TRADUCTEURS ET ASH\nAssistent le médecin : traduction (shimaoré ou shibushi), prise de paramètres si besoin, réalisation de certains tests (test optimal, Actim CRP, tétanotop...). Précieux pour comprendre l'expression culturelle de la symptomatologie.\n\nBUREAU DES ENTRÉES\nEnregistrement des patients, impression des étiquettes.\n\nIDE — répartition\n- Poste d'accueil (IAO)\n- Permanence de soins\n- Pansements (7h-19h)\n- Salle de prélèvements : injections d'insuline, bilans sanguins programmés, vaccins sur RDV (7h-14h)\n\nAS — répartition\n- Poste AO à la tente de tri (7h-14h) ou box AO (7h-19h)\n- Permanence de soins (7h-19h)\n\nSECRÉTAIRES MÉDICALES\n- En interne (Kahani) : RDV prélèvements, pansements, consultations chroniques, consultations d'après-midi\n- En externe : prises de RDV à l'hôpital de Mamoudzou pour consultations spécialisées, imagerie...\n\nSÉCURITÉ\nPrésente 7j/7, oriente les patients dans le calme — ne réalise pas le tri médical. La nuit, un interphone permet de communiquer avec les patients hors du dispensaire.\n\nRESSOURCES SPÉCIFIQUES DU DISPENSAIRE (au moment de la rédaction, à actualiser)\nIDE (Valérie Koutala) : éducation thérapeutique des diabétiques\nIPA (Sitti Abdallah) : consultations chroniques (HTA, diabète) en parallèle du médecin KRO\nDes journées de formation à la DRP sont régulièrement organisées."
  }
]